#!/usr/bin/env bash
# Reading /etc/passwd using while loop and IFS

while IFS=: read -r username _ userid groupid rest
do
	home_directory=$(echo "$rest" | cut -d: -f6)
	shell=$(echo "$rest" | cut -d: -f7)
	user_info=$(echo "$rest" | cut -d: -f5- | sed 's/[^:]*://')

	echo "The user $username is part of the $groupid gang, lives in $home_directory, and rides $shell. User ID's place is protected by the passcode x, more info about the user here: $user_info"
done < /etc/passwd

