#!/usr/bin/env bash
# this script display the content of the current directory in a list format
# Where only the part of the name after the first dash displayed

for file in *
do
	if [[ -f "$file" && ! "$file" == .* ]]
	then
		name=$(echo "$file" | cut -d '-' -f2-)
		echo "$name"
	fi
done

