#!/usr/bin/env bash
# This script that configures an Ubuntu server with the below requirements.
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker

sudo cp /etc/hosts /etc/hosts_backup

sudo bash -c 'echo "127.0.0.2       localhost" > /etc/hosts.new'
sudo bash -c 'echo "8.8.8.8         facebook.com" >> /etc/hosts.new'

sudo mv /etc/hosts.new /etc/hosts

