#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements.
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker

cp /etc/hosts ~/hosts.new

sudo sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
sudo sed -i 's/157.240.11.35/8.8.8.8/g' ~/hosts.new

cp -f ~/hosts.new /etc/hosts

