#!/usr/bin/env bash
# This script configures an Ubuntu server with the below requirements.
# facebook.com resolves to 8.8.8.8.
# The checker is running on Docker

cp /etc/hosts ~/hosts.new
sudo sh -c 'echo "127.0.0.2	localhost" >> /etc/hosts'
sudo sh -c 'echo "8.8.8.8	facebook.com" >> /etc/hosts'
cp -f ~/hosts.new /etc/hosts

