#!/usr/bin/env bash
# This script displays all active IPv4 IPs on the machine it’s executed on. 

ifconfig | grep "inet " | awk '{print $2}' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}' | grep -v '127.0.0.1'

